cadastros/urls.py
from django.urls import path
from .views import EmpresaCreate, EmpresaUpdate, EmpresaList, EmpresaDetail, EmpresaDelete
from .views import CategoriaCreate, CategoriaUpdate, CategoriaList, CategoriaDetail, CategoriaDelete
from .views import SubcategoriaCreate, SubcategoriaUpdate, SubcategoriaList, SubcategoriaDetail, SubcategoriaDelete
from .views import PromocaoCreate, PromocaoUpdate, PromocaoList, PromocaoDetail, PromocaoDelete
from .views import ProdutoCreate, ProdutoUpdate, ProdutoList, ProdutoDetail, ProdutoDelete
from .views import VendaCreate, VendaUpdate, VendaList, VendaDetail, VendaDelete
from .views import UserRegisterView, UserListView, UserUpdateView, UserDeleteView
from .views import home

urlpatterns = [

    path("cadastrar/empresa/", EmpresaCreate.as_view(), name="cadastrar-empresa"),
    path("cadastrar/categoria/", CategoriaCreate.as_view(), name="cadastrar-categoria"),
    path("cadastrar/subcategoria/", SubcategoriaCreate.as_view(), name="cadastrar-subcategoria"),
    path("cadastrar/promocao/", PromocaoCreate.as_view(), name="cadastrar-promocao"),
    path("cadastrar/produto/", ProdutoCreate.as_view(), name="cadastrar-produto"),
    path("cadastrar/venda/", VendaCreate.as_view(), name="cadastrar-venda"),


    path("editar/empresa/<int:pk>", EmpresaUpdate.as_view(), name="editar-empresa"),
    path("editar/categoria/<int:pk>", CategoriaUpdate.as_view(), name="editar-categoria"),
    path("editar/subcategoria/<int:pk>", SubcategoriaUpdate.as_view(), name="editar-subcategoria"),
    path("editar/promocao/<int:pk>", PromocaoUpdate.as_view(), name="editar-promocao"),
    path("editar/produto/<int:pk>", ProdutoUpdate.as_view(), name="editar-produto"),
    path("editar/venda/<int:pk>", VendaUpdate.as_view(), name="editar-venda"),


    path("excluir/empresa/<int:pk>/", EmpresaDelete.as_view(), name="excluir-empresa"),
    path("excluir/categoria/<int:pk>/", CategoriaDelete.as_view(), name="excluir-categoria"),
    path("excluir/subcategoria/<int:pk>/", SubcategoriaDelete.as_view(), name="excluir-subcategoria"),
    path("excluir/promocao/<int:pk>/", PromocaoDelete.as_view(), name="excluir-promocao"),
    path("excluir/produto/<int:pk>/", ProdutoDelete.as_view(), name="excluir-produto"),
    path("excluir/venda/<int:pk>/", VendaDelete.as_view(), name="excluir-venda"),


    path("listar/empresa/", EmpresaList.as_view(), name="listar-empresa"),
    path("listar/categoria/", CategoriaList.as_view(), name="listar-categoria"),
    path("listar/subcategoria/", SubcategoriaList.as_view(), name="listar-subcategoria"),
    path("listar/promocao/", PromocaoList.as_view(), name="listar-promocao"),
    path("listar/produto/", ProdutoList.as_view(), name="listar-produto"),
    path("listar/venda/", VendaList.as_view(),  name="listar-venda"),


    path("detalhar/empresa/<int:pk>/", EmpresaDetail.as_view(), name="detalhar-empresa"),
    path("detalhar/categoria/<int:pk>/", CategoriaDetail.as_view(), name="detalhar-categoria"),
    path("detalhar/subcategoria/<int:pk>/", SubcategoriaDetail.as_view(), name="detalhar-subcategoria"),
    path("detalhar/promocao/<int:pk>/",  PromocaoDetail.as_view(), name="detalhar-promocao"),
    path("detalhar/produto/<int:pk>/", ProdutoDetail.as_view(), name="detalhar-produto"),
    path("detalhar/venda/<int:pk>/", VendaDetail.as_view(), name="detalhar-venda"),

    path('register/', UserRegisterView.as_view(), name='user-register'),
    path('usuarios/', UserListView.as_view(), name='listar-usuarios'),
    path('editar/usuario/<int:pk>/', UserUpdateView.as_view(), name='editar-usuario'),
    path('excluir/usuario/<int:pk>/', UserDeleteView.as_view(), name='excluir-usuario'),

    path('', home, name='home'),
]

lojaVirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("paginas.urls")),
    path("", include("cadastros.urls")),
    path("", include("usuarios.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

paginas/urls.py
from django.urls import path
from .views import SobreView

urlpatterns = [
    path("sobre/", SobreView.as_view(), name="sobre"),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User


class Empresa(models.Model):
    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, unique=True)
    telefone = models.CharField(max_length=15)
    documento = models.CharField(max_length=18, help_text="CNPJ ou CPF")
    endereco = models.CharField(max_length=100, verbose_name="endereço")
    data_inclusao = models.DateTimeField(
        auto_now_add=True, verbose_name="data inclusão")
    data_alteracao = models.DateTimeField(
        auto_now=True, verbose_name="data alteração")
    data_exclusao = models.DateTimeField(
        verbose_name="data exclusão", null=True)
    status = models.BooleanField(default=True)
    cadastrado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='empresa_cadastrada')
    alterado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='empresa_atualizada')

    def __str__(self):
        return self.nome



class Categoria(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=100, verbose_name="descrição")
    data_inclusao = models.DateTimeField(auto_now_add=True, verbose_name="data inclusão")
    data_alteracao = models.DateTimeField(auto_now=True, verbose_name="data alteração")
    data_exclusao = models.DateTimeField(
        verbose_name="data exclusão", null=True)
    cadastrado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='categoria_cadastrada')
    alterado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='categoria_atualizada')


    def __str__(self):
        return f"{self.nome} ({self.descricao})"
    
    
class Subcategoria(models.Model):
    nome_subcategoria = models.CharField(max_length=50)
    descricao_subcategoria = models.CharField(max_length=100)
    categoria_principal = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    data_inclusao = models.DateTimeField(
        auto_now_add=True, verbose_name="data inclusão")
    data_alteracao = models.DateTimeField(
        auto_now=True, verbose_name="data alteração")
    data_exclusao = models.DateTimeField(
        verbose_name="data exclusão", null=True)
    cadastrado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='subcategoria_cadastrada')
    alterado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='subcategoria_atualizada')


    def __str__(self):
        return f"{self.nome_subcategoria} ({self.descricao_subcategoria})"

class Promocao(models.Model):
    data_inclusao = models.DateTimeField(
        auto_now_add=True, verbose_name="data inclusão")
    data_alteracao = models.DateTimeField(
        auto_now=True, verbose_name="data alteração")
    data_exclusao = models.DateTimeField(verbose_name="data exclusão", null=True)
    ativo = models.BooleanField
    titulo_promocao= models.CharField(max_length=50, verbose_name="titulo promoção")
    data_inicio= models.DateTimeField()
    data_fim = models.DateTimeField()
    descricao= models.CharField(max_length=200, verbose_name="descrição")
    valor= models.DecimalField(decimal_places=2, max_digits=11)
    cadastrado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='promocao_cadastrada')
    alterado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='promocao_atualizada')


    def __str__(self):
        return f"{self.titulo_promocao} ({self.descricao})"

    class Meta:
        verbose_name: "Promoção"

class Produto(models.Model):
    data_inclusao = models.DateTimeField(
        auto_now_add=True, verbose_name="data inclusão")
    data_alteracao = models.DateTimeField(
        auto_now=True, verbose_name="data alteração")
    data_exclusao = models.DateTimeField(
        auto_now=True, verbose_name="data exclusão")
    ativo = models.BooleanField
    nome_produto = models.CharField(max_length=50)
    descricao = models.CharField(max_length=200, verbose_name="descrição")
    preco = models.DecimalField(decimal_places=2, max_digits=11)
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.PROTECT)
    cadastrado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='produto_cadastrado')
    alterado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='produto_atualizado')
    quantidade_estoque = models.PositiveIntegerField(default=0)


    def __str__(self):
        return f"{self.nome_produto} ({self.descricao})"
    
class Venda(models.Model):
    data_inclusao = models.DateTimeField(
        auto_now_add=True, verbose_name="data inclusão")
    data_alteracao = models.DateTimeField(
        auto_now=True, verbose_name="data alteração")
    data_exclusao = models.DateTimeField(
        verbose_name="data exclusão", null=True)
    ativo = models.BooleanField
    nome_cliente = models.CharField(max_length=50)
    endereco_montagem = models.CharField(
        max_length=200, verbose_name="endereço montagem")
    telefone_cliente = models.CharField(max_length=15)
    data_venda = models.DateTimeField()
    total = models.DecimalField(decimal_places=2, max_digits=11)
    data_pagamento = models.DateTimeField()
    promocao = models.ForeignKey(Promocao, on_delete=models.PROTECT)
    pago = models.BooleanField(default=False)
    pegue_monte = models.BooleanField(default=False)
    cadastrado_por = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, related_name='venda_cadastrada')
    alterado_por = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, related_name='venda_atualizada')
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()


    def __str__(self):
        return f"{self.nome_cliente} ({self.data_venda})"
    


class MovimentoEstoque(models.Model):
    ENTRADA = 'E'
    SAIDA = 'S'

    TIPO_MOVIMENTO_CHOICES = [
        (ENTRADA, 'Entrada'),
        (SAIDA, 'Saída'),
    ]

    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    tipo_movimento = models.CharField(
        max_length=1,
        choices=TIPO_MOVIMENTO_CHOICES,
    )
    quantidade_movimentada = models.PositiveIntegerField()
    descricao = models.CharField(max_length=255)
    data_movimento = models.DateTimeField(
        auto_now=True, verbose_name="data movimento")
    
    def __str__(self):
        return f"{self.get_tipo_movimento_display()} - {self.produto.nome} - {self.quantidade_movimentada}"

cadastros/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

cadastros/templates/cadastros/delete.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h1 class="mt-5">{{titulo|default:"Exclusão"}}</h1>

<form action="" method="post">
    {% csrf_token %}

    <p>
        Tem certeza que deseja excluir: <b>{{object}}</b>
    </p>


    <button type="submit" class="btn btn-danger">Excluir</button>
</form>

{% endblock %}

cadastros/templates/cadastros/form.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{%block conteudo %}
<h1 class="mt-5">{{ titulo|default:"Formulário de cadastro e edição" }}</h1>

<form action="" method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-success">
        Salvar
    </button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

<script>
    $(document).ready(function () {
        // Aplicando o calendário ao campo "data_venda"
        $("#id_data_venda").datepicker({
            dateFormat: "dd/mm/yy"  // Formato da data
        });

        // Aplicando o calendário ao campo "data_pagamento"
        $("#id_data_pagamento").datepicker({
            dateFormat: "dd/mm/yy"  // Formato da data
        });

        // Aplicando o calendário ao campo "data_inicio"
        $("#id_data_inicio").datepicker({
            dateFormat: "dd/mm/yy"  // Formato da data
        });

        // Aplicando o calendário ao campo "data_fim"
        $("#id_data_fim").datepicker({
            dateFormat: "dd/mm/yy"  // Formato da data
        });
    });
</script>

<script>
    $(document).ready(function(){
        // Máscara para o campo de telefone
        $("#id_telefone").mask("(00) 00000-0000");
        $("#id_telefone_cliente").mask("(00) 00000-0000");

        // Máscara para o campo de e-mail
        $("#id_email").on('blur', function(){
            var email = $(this).val();

            if (!/\S+@\S+\.\S+/.test(email)) {
                alert('Por favor, insira um e-mail válido.');
            }
        });
    });
</script>

<script>
    $(document).ready(function(){
        // Aplicando máscara para CPF ou CNPJ
        $("#id_documento").on('input', function(){
            var valor = $(this).val().replace(/\D/g, '');
            // Verificar se o valor tem 11 ou 14 dígitos
            if (valor.length >= 11) {
                // Máscara para CNPJ (xx.xxx.xxx/xxxx-xx)
                $(this).mask("00.000.000/0000-00");
                
            } else {
                // Máscara para CPF (xxx.xxx.xxx-xx)
                $(this).mask("000.000.000-00");
            }
        });
    });
</script>

{% endblock %}